name: e_commerce
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  responsive_framework:
  get:
  http:
  provider:
  flutter_secure_storage:
  fluttertoast:
  flutter_screenutil: ^5.5.3+2
  video_player: any
  google_fonts:
  iconly: ^1.0.1
  cached_network_image: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
flutter:
  uses-material-design: true
  assets:
    - asset/icon/


